---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.6
    run_list:
    - recipe[yum]
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]
  - name: ubuntu-14.04
    run_list:
    - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[rackspace_nginx_php_test::default]
  - name: php54
    run_list:
      - recipe[rackspace_nginx_php_test::default]
    attributes:
      rackspace_nginx_php:
        php_version: '5.4'
  - name: php54_override
    run_list:
      - recipe[rackspace_nginx_php_test::override]
    attributes:
      rackspace_nginx_php:
        php_version: '5.4'  
  - name: php55
    run_list:
      - recipe[rackspace_nginx_php_test::default]
    attributes:
      rackspace_nginx_php:
        php_version: '5.5'
  - name: php55_override
    run_list:
      - recipe[rackspace_nginx_php_test::override]
    attributes:
      rackspace_nginx_php:
        php_version: '5.5'
  - name: php56
    run_list:
      - recipe[rackspace_nginx_php_test::default]
    attributes:
      rackspace_nginx_php:
        php_version: '5.6'
  - name: php56_override
    run_list:
      - recipe[rackspace_nginx_php_test::override]
    attributes:
      rackspace_nginx_php:
        php_version: '5.6'